Repository adaptlearning/adapt-contrib-boxMenu, pull requests merged in 2023-02, with the labels that each got.

#135 Fix: Add option to add a graphic to the menu header (fixes #133)
  README.md
  example.json
  less/boxMenu.less
  properties.schema
  schema/course.schema.json
  templates/boxMenu.hbs
Labels: enhancement

#136 New: Adds locking icon to locked menu items (fixes: #134)
  less/boxMenuItem.less
  templates/boxMenuItem.hbs
Labels: enhancement

#139 Fix: Normalizing template icons (fixes: #138)
  templates/boxMenuItem.hbs
Labels: accessibility

#141 Fix: Standardise aria-label with updated component aria-label
  js/BoxMenuView.js
  templates/boxMenuItem.hbs
Labels: bug, accessibility
