Repository adaptlearning/adapt-contrib-boxMenu, pull requests merged in 2024-04, with the labels that each got.

#186 Fix: Change from Adapt.device to device directly
  js/BoxMenuView.js
Labels: bug

#187 Fix: Add xlarge props to documentation (fixes #184)
  README.md
  example.json
Labels: documentation

#190 New: Complete icon styling added (fixes #189)
  less/boxMenuItem.less
Labels: enhancement
